### ISSUE TITLE
Replace lsp plugin from coc.nvim to builtin-lsp

### ISSUE THREAD

**Issue by nnsnico** [nnsnico/dotfiles#3]
## migration list (macOS)

| coc.nvim                        | nvim-lsp-installer                                                                                                        |
|---------------------------------|---------------------------------------------------------------------------------------------------------------------------|
| `coc-clangd`                    | `clangd`                                                                                                                  |
| `coc-eslint`                    | `eslint`                                                                                                                  |
| `coc-flutter`                   | `dartls` , `akinsho/flutter-tools.nvim`                                                                                   |
| `coc-go`                        | `gopls`                                                                                                                   |
| `coc-json`                      | `jsonls`                                                                                                                  |
| `coc-markdown-preview-enhanced` | none (alternative: https://github.com/iamcco/markdown-preview.nvim)                                                       |
| `coc-markdownlint`              | `zeta-note`                                                                                                               |
| `coc-metals`                    | none (should install `nvim-metals` manualy from lspconfig)                                                                |
| `coc-phpls`                     | `intelephense`                                                                                                            |
| `coc-prettier`                  | none (should install `prettier.nvim` manualy from lspconfig)                                                              |
| `coc-python`                    | `pyright`                                                                                                                 |
| `coc-rls`                       | `rust_analyzer`                                                                                                           |
| `coc-sh`                        | `bashls`                                                                                                                  |
| `coc-solargraph`                | `solargraph`                                                                                                              |
| `coc-sumneko-lua`               | `sumneko_lua` (also setting to apply vim api) [good reference](https://jdhao.github.io/2021/08/12/nvim_sumneko_lua_conf/) |
| `coc-tsserver`                  | `tsserver`                                                                                                                |
| `coc-vimlsp`                    | `vimls`                                                                                                                   |
| `coc-webview`                   | none                                                                                                                      |
| `coc-yaml`                      | `yamlls`                                                                                                                  |

### minimum required plugin

- [`neovim/nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig)
- [`williamboman/nvim-lsp-installer`](https://github.com/williamboman/nvim-lsp-installer)

### TODO after migration

- [x] Remove coc.nvim
  - also coc.lua
- [x] Remove coc-config.json
- [x] Improve quickrun configurations
  - To use on nvim-lspconfig
